---
- name: Provision a set of instances
  ec2:
    key_name: Ansible
    group: default
    instance_type: t2.micro
    image: ami-6871a115
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
       Name: Demo
    instance_tags:
       Name: WSO2EI-Node
    region: us-east-1
  register: ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=ec2hosts ansible_ssh_private_key_file=Ansible.pem
  loop: "{{ ec2.instances }}"
- name: Waiting for the instance to come
  local_action: wait_for
                  host={{ item.public_ip }}
                  state=started
                  port=22
  with_items: "{{ ec2.instances }}"
      