---
- name: Ensure user "wso2" exists
  become_user: root
  become: true
  user:
    name: wso2
    state: present
  ignore_errors: no

- name: Check if wso2ei file is already configured.
  stat: path={{wso2ei_file_path}}
  #connection: local
  register: wso2ei_file_result

- name: "copy the wso2ei package to machine"
  get_url:
    url: "{{wso2ei_path}}"
    dest: "{{wso2ei_file_path}}"
  when: not wso2ei_file_result.stat.exists

- name: "install unzip"
  become_user: root
  become: true
  yum: 
    name: unzip
    state: installed
  
- name: check /opt/app not exist,create directory"
  become_user: root
  become: true
  stat: path={{application_home}}
  ignore_errors: True
  register: application_home_result  

- shell: mkdir {{application_home}}
  become_user: root
  become: true
  when: not application_home_result.stat.exists

- name: "unpack the wso2ei package to /opt/app"
  become_user: root
  become: true
  unarchive:
    copy: no
    src: "{{ wso2ei_file_path }}"
    dest: "{{application_home}}"

- name: "chang wso2 home owner"
  become_user: root
  become: true
  command: >
    chown -R wso2:wso2 {{application_home}}/{{wso2ei_home}}

- name: copy the wso2ei server.sh to machine
  become_user: root
  become: true
  template:
      src: wso2ei.j2
      dest: /etc/init.d/wso2ei
      mode: 0755

- name: "Start wso2 ei"
  become_user: root
  become: true
  service:
    name: wso2ei
    state: started
    enabled: yes
